name: Javascript_workflows

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # You can specify any version you need

      - name: Run Javascript program
        run: node my.js

      - name: Run tests
        run: npm test
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        id: ['archita_sharma']  # Manually provided ID
- name: Run Javascript program
        run: |
          echo "Using ID: ${{ matrix.id }}"
          
  example_environment variables:
  runs-on: ubuntu-latest
  env:
  First_variable : "12345"


  steps:
  -name: Print variable
   run: echo "first_variable:-->$first variable"
